Added r/riprequest along with blockthespot
rippedpiracy/docs pull request #23
Opened 2021-12-20 06:25 UTC by Father-Dimi

decided to stop being lazy and added them

2021-12-20 06:31 UTC, Father-Dimi commented
also added vimms lair to rom

2021-12-20 13:02 UTC, kekkodance commented
you stoopid vimms "liar" is already in roms

2021-12-20 13:03 UTC, kekkodance commented
also fix your gremmer

2021-12-21 01:11 UTC, doggo404 commented
> you stoopid vimms "liar" is already in roms

calm down fool

2021-12-21 01:15 UTC, doggo404 requested changes
god
help
us 
all

2021-12-21 01:15 UTC, doggo404 commented on Music/music.md
> +[**R/RipRequest**](https://www.reddit.com/r/riprequests/) - A sub-reddit for requesting songs (most flacs) **_Is currently private but you can request access_**
change sub-reddit to subreddit, change "requesting songs (most flacs)"  to "requesting lossless rips of albums"

2021-12-21 01:15 UTC, doggo404 commented on Music/music.md
> +
"Modified Spotify client to unlock unlock features without premium"

2021-12-21 02:54 UTC, Father-Dimi commented
Alright, ill fix some stuff for it

2021-12-21 03:07 UTC, Father-Dimi commented
also, do you guys think we should add crackedmultimc? and if we should put it in games or accounts?

2021-12-23 13:46 UTC, Father-Dimi commented
updated music again due to rip request closing

2021-12-23 15:03 UTC, Helmasko commented
All these have been implemented finally, if you have any other suggestions to add, make a new issue/pull request (and for gods sake dont make a whole new file to add 1 line)

2021-12-23 15:03 UTC, closed without merging